# Generated by Django 4.2.1 on 2023-06-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(default=1, null=True, upload_to='cource/')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Лёгкий'), (2, 'Продвинутый'), (3, 'Профильный'), (4, 'Специалитет')], default=2, verbose_name='Уровень')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course', models.ManyToManyField(related_name='courses', to='course.course')),
            ],
        ),
    ]
